d-bus cleanups
svn path=/trunk/; revision=49

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -948,8 +948,8 @@ GCONF_SCHEMAS_INSTALL_TRUE
 GCONF_SCHEMAS_INSTALL_FALSE
 DBUS_CFLAGS
 DBUS_LIBS
-DBUS_VERSION
-HAVE_DBUS
+HAVE_DBUS_TRUE
+HAVE_DBUS_FALSE
 GETTEXT
 GETTEXT_PACKAGE
 USE_NLS
@@ -1594,6 +1594,7 @@ Optional Features:
   --disable-webkit        Disable Webkit (Apple's Upstream Webkit) support
                           (default: enabled)
   --disable-schemas-install	Disable the schemas installation
+  --disable-dbus          Disable D-BUS support (default: enabled)
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -6098,7 +6099,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6101 "configure"' > conftest.$ac_ext
+  echo '#line 6102 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -8436,11 +8437,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8439: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8440: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8443: \$? = $ac_status" >&5
+   echo "$as_me:8444: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8726,11 +8727,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8729: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8730: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8733: \$? = $ac_status" >&5
+   echo "$as_me:8734: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8830,11 +8831,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8833: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8834: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8837: \$? = $ac_status" >&5
+   echo "$as_me:8838: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11181,7 +11182,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11184 "configure"
+#line 11185 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11281,7 +11282,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11284 "configure"
+#line 11285 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13701,11 +13702,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13704: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13705: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13708: \$? = $ac_status" >&5
+   echo "$as_me:13709: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13805,11 +13806,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13808: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13809: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13812: \$? = $ac_status" >&5
+   echo "$as_me:13813: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15369,11 +15370,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15372: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15373: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15376: \$? = $ac_status" >&5
+   echo "$as_me:15377: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15473,11 +15474,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15476: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15477: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15480: \$? = $ac_status" >&5
+   echo "$as_me:15481: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17662,11 +17663,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17665: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17666: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17669: \$? = $ac_status" >&5
+   echo "$as_me:17670: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17952,11 +17953,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17955: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17956: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17959: \$? = $ac_status" >&5
+   echo "$as_me:17960: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -18056,11 +18057,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18059: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18060: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:18063: \$? = $ac_status" >&5
+   echo "$as_me:18064: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -22062,6 +22063,14 @@ fi
 
 
 
+have_dbus=no
+# Check whether --enable-DBUS was given.
+if test "${enable_DBUS+set}" = set; then
+  enableval=$enable_DBUS;
+fi
+
+
+if test "x$enable_dbus" != "xno"; then
 
 pkg_failed=no
 { echo "$as_me:$LINENO: checking for DBUS" >&5
@@ -22135,19 +22144,13 @@ echo "${ECHO_T}yes" >&6; }
 fi
 
 
-
-# Get the version of the DBus API, so we can hack around API changes until the API stabilises:
-# multiply by 1000 to convert decimal to integer; so e.g. 0.31 become 310
-# since preprocessor values must be integral
-DBUS_VERSION="`pkg-config --modversion dbus-1 | awk '{print 1000 * $1}'`"
-
-echo $DBUS_VERSION
-if test "x$have_dbus" != "xno"; then
-
-cat >>confdefs.h <<_ACEOF
-#define HAVE_DBUS 1
-_ACEOF
-
+fi
+ if test x$have_dbus = xyes; then
+  HAVE_DBUS_TRUE=
+  HAVE_DBUS_FALSE='#'
+else
+  HAVE_DBUS_TRUE='#'
+  HAVE_DBUS_FALSE=
 fi
 
 
@@ -23780,7 +23783,7 @@ fi
 serverdir="$BONOBO_LIBDIR/bonobo/servers"
 
 
-privdatadir='${datadir}'/evolution/$EVOLUTION_BASE_VERSION
+privdatadir='${datadir}'/evolution/$EVOLUTION_EXEC_VERSION
 
 
 gladedir="$privdatadir/glade"
@@ -23795,8 +23798,9 @@ if test "x$have_webkit" != "xno" -a "$enable_webkit" = "yes"; then
         kits=$kits"WebKit, "
 fi
 kits="$kits$gecko_cv_gecko (gecko engine version $gecko_cv_gecko_version)"
-if test "x$have_dbus" != "xno"; then
-	have_dbus_build="evolution-import-rss module will be built"
+
+if test "x$have_dbus" == "xyes"; then
+	have_dbus_build="yes"
 	import_feeds="evolution-import-rss"
 else
 	have_dbus_build="evolution-import-rss module will be not built"
@@ -23984,6 +23988,13 @@ if test -z "${GCONF_SCHEMAS_INSTALL_TRUE}" && test -z "${GCONF_SCHEMAS_INSTALL_F
   { { echo "$as_me:$LINENO: error: conditional \"GCONF_SCHEMAS_INSTALL\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"GCONF_SCHEMAS_INSTALL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HAVE_DBUS_TRUE}" && test -z "${HAVE_DBUS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_DBUS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_DBUS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -24759,8 +24770,8 @@ GCONF_SCHEMAS_INSTALL_TRUE!$GCONF_SCHEMAS_INSTALL_TRUE$ac_delim
 GCONF_SCHEMAS_INSTALL_FALSE!$GCONF_SCHEMAS_INSTALL_FALSE$ac_delim
 DBUS_CFLAGS!$DBUS_CFLAGS$ac_delim
 DBUS_LIBS!$DBUS_LIBS$ac_delim
-DBUS_VERSION!$DBUS_VERSION$ac_delim
-HAVE_DBUS!$HAVE_DBUS$ac_delim
+HAVE_DBUS_TRUE!$HAVE_DBUS_TRUE$ac_delim
+HAVE_DBUS_FALSE!$HAVE_DBUS_FALSE$ac_delim
 GETTEXT!$GETTEXT$ac_delim
 GETTEXT_PACKAGE!$GETTEXT_PACKAGE$ac_delim
 USE_NLS!$USE_NLS$ac_delim
@@ -25478,7 +25489,7 @@ echo "
 	Prefix			: $prefix
 	HTML renders		: $kits
 	Primary HTML render	: $RENDER
-	D-BUS support		: $have_dbus ($have_dbus_build)
+	D-BUS support		: $have_dbus_build
 	Import feeds		: $import_feeds
 
 	"
